set shell := ["cmd.exe", "/c"]


build:
    rm -fr dist/*
    cargo build --target wasm32-unknown-unknown
    wasm-bindgen --no-typescript --target web \
        --out-dir ./dist/ \
        --out-name frontend \
        ./target/wasm32-unknown-unknown/debug/frontend.wasm
    cp -r static/* dist
    
build-release:
    rm -fr dist/*
    cargo build --release --target wasm32-unknown-unknown
    wasm-bindgen --no-typescript --target web \
        --out-dir ./dist/ \
        --out-name frontend \
        ./target/wasm32-unknown-unknown/debug/frontend.wasm
    cp -r static/* dist

wasm-opt:
	wasm-opt -Os -o ./dist/frontend_bg.wasm ./dist/frontend_bg.wasm
