// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: client_packet.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientEvent_ClientEventType int32

const (
	ClientEvent_CLIENT_EVENT_TYPE_UNSPECIFIED ClientEvent_ClientEventType = 0
	ClientEvent_MOVE                          ClientEvent_ClientEventType = 1
	ClientEvent_START_FIRE                    ClientEvent_ClientEventType = 2
	ClientEvent_STOP_FIRE                     ClientEvent_ClientEventType = 3
	ClientEvent_CAST_SPELL                    ClientEvent_ClientEventType = 4
)

// Enum value maps for ClientEvent_ClientEventType.
var (
	ClientEvent_ClientEventType_name = map[int32]string{
		0: "CLIENT_EVENT_TYPE_UNSPECIFIED",
		1: "MOVE",
		2: "START_FIRE",
		3: "STOP_FIRE",
		4: "CAST_SPELL",
	}
	ClientEvent_ClientEventType_value = map[string]int32{
		"CLIENT_EVENT_TYPE_UNSPECIFIED": 0,
		"MOVE":                          1,
		"START_FIRE":                    2,
		"STOP_FIRE":                     3,
		"CAST_SPELL":                    4,
	}
)

func (x ClientEvent_ClientEventType) Enum() *ClientEvent_ClientEventType {
	p := new(ClientEvent_ClientEventType)
	*p = x
	return p
}

func (x ClientEvent_ClientEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientEvent_ClientEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_client_packet_proto_enumTypes[0].Descriptor()
}

func (ClientEvent_ClientEventType) Type() protoreflect.EnumType {
	return &file_client_packet_proto_enumTypes[0]
}

func (x ClientEvent_ClientEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientEvent_ClientEventType.Descriptor instead.
func (ClientEvent_ClientEventType) EnumDescriptor() ([]byte, []int) {
	return file_client_packet_proto_rawDescGZIP(), []int{0, 0}
}

type ClientEvent struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Type          ClientEvent_ClientEventType `protobuf:"varint,1,opt,name=type,proto3,enum=spellfire.ClientEvent_ClientEventType" json:"type,omitempty"`
	Timestamp     *Timestamp                  `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Movement      *Vec2                       `protobuf:"bytes,4,opt,name=movement,proto3" json:"movement,omitempty"`
	Spell         Spell                       `protobuf:"varint,6,opt,name=spell,proto3,enum=spellfire.Spell" json:"spell,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientEvent) Reset() {
	*x = ClientEvent{}
	mi := &file_client_packet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientEvent) ProtoMessage() {}

func (x *ClientEvent) ProtoReflect() protoreflect.Message {
	mi := &file_client_packet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientEvent.ProtoReflect.Descriptor instead.
func (*ClientEvent) Descriptor() ([]byte, []int) {
	return file_client_packet_proto_rawDescGZIP(), []int{0}
}

func (x *ClientEvent) GetType() ClientEvent_ClientEventType {
	if x != nil {
		return x.Type
	}
	return ClientEvent_CLIENT_EVENT_TYPE_UNSPECIFIED
}

func (x *ClientEvent) GetTimestamp() *Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ClientEvent) GetMovement() *Vec2 {
	if x != nil {
		return x.Movement
	}
	return nil
}

func (x *ClientEvent) GetSpell() Spell {
	if x != nil {
		return x.Spell
	}
	return Spell_SPELL_FIREBALL
}

type ClientPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        *Vec2                  `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Events        []*ClientEvent         `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientPacket) Reset() {
	*x = ClientPacket{}
	mi := &file_client_packet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientPacket) ProtoMessage() {}

func (x *ClientPacket) ProtoReflect() protoreflect.Message {
	mi := &file_client_packet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientPacket.ProtoReflect.Descriptor instead.
func (*ClientPacket) Descriptor() ([]byte, []int) {
	return file_client_packet_proto_rawDescGZIP(), []int{1}
}

func (x *ClientPacket) GetCursor() *Vec2 {
	if x != nil {
		return x.Cursor
	}
	return nil
}

func (x *ClientPacket) GetEvents() []*ClientEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_client_packet_proto protoreflect.FileDescriptor

const file_client_packet_proto_rawDesc = "" +
	"\n" +
	"\x13client_packet.proto\x12\tspellfire\x1a\vtypes.proto\x1a\n" +
	"mage.proto\"\xc1\x02\n" +
	"\vClientEvent\x12:\n" +
	"\x04type\x18\x01 \x01(\x0e2&.spellfire.ClientEvent.ClientEventTypeR\x04type\x122\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x14.spellfire.TimestampR\ttimestamp\x12+\n" +
	"\bmovement\x18\x04 \x01(\v2\x0f.spellfire.Vec2R\bmovement\x12&\n" +
	"\x05spell\x18\x06 \x01(\x0e2\x10.spellfire.SpellR\x05spell\"m\n" +
	"\x0fClientEventType\x12!\n" +
	"\x1dCLIENT_EVENT_TYPE_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04MOVE\x10\x01\x12\x0e\n" +
	"\n" +
	"START_FIRE\x10\x02\x12\r\n" +
	"\tSTOP_FIRE\x10\x03\x12\x0e\n" +
	"\n" +
	"CAST_SPELL\x10\x04\"g\n" +
	"\fClientPacket\x12'\n" +
	"\x06cursor\x18\x02 \x01(\v2\x0f.spellfire.Vec2R\x06cursor\x12.\n" +
	"\x06events\x18\x03 \x03(\v2\x16.spellfire.ClientEventR\x06eventsB?Z=github.com/Icemaster-Eric/Spellfire/backend/internal/proto;pbb\x06proto3"

var (
	file_client_packet_proto_rawDescOnce sync.Once
	file_client_packet_proto_rawDescData []byte
)

func file_client_packet_proto_rawDescGZIP() []byte {
	file_client_packet_proto_rawDescOnce.Do(func() {
		file_client_packet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_packet_proto_rawDesc), len(file_client_packet_proto_rawDesc)))
	})
	return file_client_packet_proto_rawDescData
}

var file_client_packet_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_client_packet_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_client_packet_proto_goTypes = []any{
	(ClientEvent_ClientEventType)(0), // 0: spellfire.ClientEvent.ClientEventType
	(*ClientEvent)(nil),              // 1: spellfire.ClientEvent
	(*ClientPacket)(nil),             // 2: spellfire.ClientPacket
	(*Timestamp)(nil),                // 3: spellfire.Timestamp
	(*Vec2)(nil),                     // 4: spellfire.Vec2
	(Spell)(0),                       // 5: spellfire.Spell
}
var file_client_packet_proto_depIdxs = []int32{
	0, // 0: spellfire.ClientEvent.type:type_name -> spellfire.ClientEvent.ClientEventType
	3, // 1: spellfire.ClientEvent.timestamp:type_name -> spellfire.Timestamp
	4, // 2: spellfire.ClientEvent.movement:type_name -> spellfire.Vec2
	5, // 3: spellfire.ClientEvent.spell:type_name -> spellfire.Spell
	4, // 4: spellfire.ClientPacket.cursor:type_name -> spellfire.Vec2
	1, // 5: spellfire.ClientPacket.events:type_name -> spellfire.ClientEvent
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_client_packet_proto_init() }
func file_client_packet_proto_init() {
	if File_client_packet_proto != nil {
		return
	}
	file_types_proto_init()
	file_mage_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_packet_proto_rawDesc), len(file_client_packet_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_client_packet_proto_goTypes,
		DependencyIndexes: file_client_packet_proto_depIdxs,
		EnumInfos:         file_client_packet_proto_enumTypes,
		MessageInfos:      file_client_packet_proto_msgTypes,
	}.Build()
	File_client_packet_proto = out.File
	file_client_packet_proto_goTypes = nil
	file_client_packet_proto_depIdxs = nil
}
