// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: server_packet.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Gun int32

const (
	Gun_GUN_UNSPECIFIED     Gun = 0
	Gun_GUN_AUTOMATIC_RIFLE Gun = 1
)

// Enum value maps for Gun.
var (
	Gun_name = map[int32]string{
		0: "GUN_UNSPECIFIED",
		1: "GUN_AUTOMATIC_RIFLE",
	}
	Gun_value = map[string]int32{
		"GUN_UNSPECIFIED":     0,
		"GUN_AUTOMATIC_RIFLE": 1,
	}
)

func (x Gun) Enum() *Gun {
	p := new(Gun)
	*p = x
	return p
}

func (x Gun) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Gun) Descriptor() protoreflect.EnumDescriptor {
	return file_server_packet_proto_enumTypes[0].Descriptor()
}

func (Gun) Type() protoreflect.EnumType {
	return &file_server_packet_proto_enumTypes[0]
}

func (x Gun) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Gun.Descriptor instead.
func (Gun) EnumDescriptor() ([]byte, []int) {
	return file_server_packet_proto_rawDescGZIP(), []int{0}
}

type Collider_ColliderType int32

const (
	Collider_COLLIDER_TYPE_UNSPECIFIED Collider_ColliderType = 0
	Collider_POINT                     Collider_ColliderType = 1
	Collider_CIRCLE                    Collider_ColliderType = 2
	Collider_RECT                      Collider_ColliderType = 3
)

// Enum value maps for Collider_ColliderType.
var (
	Collider_ColliderType_name = map[int32]string{
		0: "COLLIDER_TYPE_UNSPECIFIED",
		1: "POINT",
		2: "CIRCLE",
		3: "RECT",
	}
	Collider_ColliderType_value = map[string]int32{
		"COLLIDER_TYPE_UNSPECIFIED": 0,
		"POINT":                     1,
		"CIRCLE":                    2,
		"RECT":                      3,
	}
)

func (x Collider_ColliderType) Enum() *Collider_ColliderType {
	p := new(Collider_ColliderType)
	*p = x
	return p
}

func (x Collider_ColliderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Collider_ColliderType) Descriptor() protoreflect.EnumDescriptor {
	return file_server_packet_proto_enumTypes[1].Descriptor()
}

func (Collider_ColliderType) Type() protoreflect.EnumType {
	return &file_server_packet_proto_enumTypes[1]
}

func (x Collider_ColliderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Collider_ColliderType.Descriptor instead.
func (Collider_ColliderType) EnumDescriptor() ([]byte, []int) {
	return file_server_packet_proto_rawDescGZIP(), []int{0, 0}
}

type RenderData_Sprite int32

const (
	RenderData_SPRITE_UNSPECIFIED RenderData_Sprite = 0
	RenderData_GUNNER             RenderData_Sprite = 1
	RenderData_MAGE               RenderData_Sprite = 2
	RenderData_BULLET_1           RenderData_Sprite = 3
	RenderData_BUSH_1             RenderData_Sprite = 4
	RenderData_TREE_1             RenderData_Sprite = 5
	RenderData_TREE_2             RenderData_Sprite = 6
	RenderData_ROCK_1             RenderData_Sprite = 7
	RenderData_ROCK_2             RenderData_Sprite = 8
	RenderData_ROCK_3             RenderData_Sprite = 9
	RenderData_ROCK_4             RenderData_Sprite = 10
	RenderData_DEAD_BUSH_1        RenderData_Sprite = 11
	RenderData_DEAD_BUSH_2        RenderData_Sprite = 12
	RenderData_CACTUS_1           RenderData_Sprite = 13
)

// Enum value maps for RenderData_Sprite.
var (
	RenderData_Sprite_name = map[int32]string{
		0:  "SPRITE_UNSPECIFIED",
		1:  "GUNNER",
		2:  "MAGE",
		3:  "BULLET_1",
		4:  "BUSH_1",
		5:  "TREE_1",
		6:  "TREE_2",
		7:  "ROCK_1",
		8:  "ROCK_2",
		9:  "ROCK_3",
		10: "ROCK_4",
		11: "DEAD_BUSH_1",
		12: "DEAD_BUSH_2",
		13: "CACTUS_1",
	}
	RenderData_Sprite_value = map[string]int32{
		"SPRITE_UNSPECIFIED": 0,
		"GUNNER":             1,
		"MAGE":               2,
		"BULLET_1":           3,
		"BUSH_1":             4,
		"TREE_1":             5,
		"TREE_2":             6,
		"ROCK_1":             7,
		"ROCK_2":             8,
		"ROCK_3":             9,
		"ROCK_4":             10,
		"DEAD_BUSH_1":        11,
		"DEAD_BUSH_2":        12,
		"CACTUS_1":           13,
	}
)

func (x RenderData_Sprite) Enum() *RenderData_Sprite {
	p := new(RenderData_Sprite)
	*p = x
	return p
}

func (x RenderData_Sprite) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RenderData_Sprite) Descriptor() protoreflect.EnumDescriptor {
	return file_server_packet_proto_enumTypes[2].Descriptor()
}

func (RenderData_Sprite) Type() protoreflect.EnumType {
	return &file_server_packet_proto_enumTypes[2]
}

func (x RenderData_Sprite) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RenderData_Sprite.Descriptor instead.
func (RenderData_Sprite) EnumDescriptor() ([]byte, []int) {
	return file_server_packet_proto_rawDescGZIP(), []int{1, 0}
}

type EntityAttribute_EntityAttributeType int32

const (
	EntityAttribute_ENTITY_ATTRIBUTE_TYPE_UNSPECIFIED EntityAttribute_EntityAttributeType = 0
	EntityAttribute_NAME                              EntityAttribute_EntityAttributeType = 1
	EntityAttribute_HEALTH                            EntityAttribute_EntityAttributeType = 2
	EntityAttribute_GUN                               EntityAttribute_EntityAttributeType = 3
	EntityAttribute_DAMAGE                            EntityAttribute_EntityAttributeType = 4
	EntityAttribute_SPELL_1_LAST_FIRE                 EntityAttribute_EntityAttributeType = 5
	EntityAttribute_SPELL_2_LAST_FIRE                 EntityAttribute_EntityAttributeType = 6
	EntityAttribute_SPELL_3_LAST_FIRE                 EntityAttribute_EntityAttributeType = 7
)

// Enum value maps for EntityAttribute_EntityAttributeType.
var (
	EntityAttribute_EntityAttributeType_name = map[int32]string{
		0: "ENTITY_ATTRIBUTE_TYPE_UNSPECIFIED",
		1: "NAME",
		2: "HEALTH",
		3: "GUN",
		4: "DAMAGE",
		5: "SPELL_1_LAST_FIRE",
		6: "SPELL_2_LAST_FIRE",
		7: "SPELL_3_LAST_FIRE",
	}
	EntityAttribute_EntityAttributeType_value = map[string]int32{
		"ENTITY_ATTRIBUTE_TYPE_UNSPECIFIED": 0,
		"NAME":                              1,
		"HEALTH":                            2,
		"GUN":                               3,
		"DAMAGE":                            4,
		"SPELL_1_LAST_FIRE":                 5,
		"SPELL_2_LAST_FIRE":                 6,
		"SPELL_3_LAST_FIRE":                 7,
	}
)

func (x EntityAttribute_EntityAttributeType) Enum() *EntityAttribute_EntityAttributeType {
	p := new(EntityAttribute_EntityAttributeType)
	*p = x
	return p
}

func (x EntityAttribute_EntityAttributeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntityAttribute_EntityAttributeType) Descriptor() protoreflect.EnumDescriptor {
	return file_server_packet_proto_enumTypes[3].Descriptor()
}

func (EntityAttribute_EntityAttributeType) Type() protoreflect.EnumType {
	return &file_server_packet_proto_enumTypes[3]
}

func (x EntityAttribute_EntityAttributeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntityAttribute_EntityAttributeType.Descriptor instead.
func (EntityAttribute_EntityAttributeType) EnumDescriptor() ([]byte, []int) {
	return file_server_packet_proto_rawDescGZIP(), []int{2, 0}
}

type Entity_EntityType int32

const (
	Entity_ENTITY_TYPE_UNSPECIFIED Entity_EntityType = 0
	Entity_GUNNER                  Entity_EntityType = 1
	Entity_MAGE                    Entity_EntityType = 2
	Entity_BULLET                  Entity_EntityType = 3
	Entity_BUSH                    Entity_EntityType = 4
	Entity_TREE                    Entity_EntityType = 5
	Entity_ROCK                    Entity_EntityType = 6
	Entity_DEAD_BUSH               Entity_EntityType = 7
	Entity_CACTUS                  Entity_EntityType = 8
)

// Enum value maps for Entity_EntityType.
var (
	Entity_EntityType_name = map[int32]string{
		0: "ENTITY_TYPE_UNSPECIFIED",
		1: "GUNNER",
		2: "MAGE",
		3: "BULLET",
		4: "BUSH",
		5: "TREE",
		6: "ROCK",
		7: "DEAD_BUSH",
		8: "CACTUS",
	}
	Entity_EntityType_value = map[string]int32{
		"ENTITY_TYPE_UNSPECIFIED": 0,
		"GUNNER":                  1,
		"MAGE":                    2,
		"BULLET":                  3,
		"BUSH":                    4,
		"TREE":                    5,
		"ROCK":                    6,
		"DEAD_BUSH":               7,
		"CACTUS":                  8,
	}
)

func (x Entity_EntityType) Enum() *Entity_EntityType {
	p := new(Entity_EntityType)
	*p = x
	return p
}

func (x Entity_EntityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Entity_EntityType) Descriptor() protoreflect.EnumDescriptor {
	return file_server_packet_proto_enumTypes[4].Descriptor()
}

func (Entity_EntityType) Type() protoreflect.EnumType {
	return &file_server_packet_proto_enumTypes[4]
}

func (x Entity_EntityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Entity_EntityType.Descriptor instead.
func (Entity_EntityType) EnumDescriptor() ([]byte, []int) {
	return file_server_packet_proto_rawDescGZIP(), []int{3, 0}
}

type Entity_EntityState int32

const (
	Entity_ENTITY_STATE_UNSPECIFIED Entity_EntityState = 0
)

// Enum value maps for Entity_EntityState.
var (
	Entity_EntityState_name = map[int32]string{
		0: "ENTITY_STATE_UNSPECIFIED",
	}
	Entity_EntityState_value = map[string]int32{
		"ENTITY_STATE_UNSPECIFIED": 0,
	}
)

func (x Entity_EntityState) Enum() *Entity_EntityState {
	p := new(Entity_EntityState)
	*p = x
	return p
}

func (x Entity_EntityState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Entity_EntityState) Descriptor() protoreflect.EnumDescriptor {
	return file_server_packet_proto_enumTypes[5].Descriptor()
}

func (Entity_EntityState) Type() protoreflect.EnumType {
	return &file_server_packet_proto_enumTypes[5]
}

func (x Entity_EntityState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Entity_EntityState.Descriptor instead.
func (Entity_EntityState) EnumDescriptor() ([]byte, []int) {
	return file_server_packet_proto_rawDescGZIP(), []int{3, 1}
}

type ServerEvent_ServerEventType int32

const (
	ServerEvent_SERVER_EVENT_TYPE_UNSPECIFIED ServerEvent_ServerEventType = 0
	ServerEvent_ENTER_GAME                    ServerEvent_ServerEventType = 1
)

// Enum value maps for ServerEvent_ServerEventType.
var (
	ServerEvent_ServerEventType_name = map[int32]string{
		0: "SERVER_EVENT_TYPE_UNSPECIFIED",
		1: "ENTER_GAME",
	}
	ServerEvent_ServerEventType_value = map[string]int32{
		"SERVER_EVENT_TYPE_UNSPECIFIED": 0,
		"ENTER_GAME":                    1,
	}
)

func (x ServerEvent_ServerEventType) Enum() *ServerEvent_ServerEventType {
	p := new(ServerEvent_ServerEventType)
	*p = x
	return p
}

func (x ServerEvent_ServerEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerEvent_ServerEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_server_packet_proto_enumTypes[6].Descriptor()
}

func (ServerEvent_ServerEventType) Type() protoreflect.EnumType {
	return &file_server_packet_proto_enumTypes[6]
}

func (x ServerEvent_ServerEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerEvent_ServerEventType.Descriptor instead.
func (ServerEvent_ServerEventType) EnumDescriptor() ([]byte, []int) {
	return file_server_packet_proto_rawDescGZIP(), []int{4, 0}
}

type Collider struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          Collider_ColliderType  `protobuf:"varint,1,opt,name=type,proto3,enum=spellfire.Collider_ColliderType" json:"type,omitempty"`
	Rotation      float64                `protobuf:"fixed64,2,opt,name=rotation,proto3" json:"rotation,omitempty"`
	Size          *Vec2                  `protobuf:"bytes,3,opt,name=size,proto3" json:"size,omitempty"`
	Radius        float64                `protobuf:"fixed64,4,opt,name=radius,proto3" json:"radius,omitempty"`
	Position      *Vec2                  `protobuf:"bytes,5,opt,name=position,proto3" json:"position,omitempty"`
	Velocity      *Vec2                  `protobuf:"bytes,6,opt,name=velocity,proto3" json:"velocity,omitempty"`
	IsStatic      bool                   `protobuf:"varint,7,opt,name=is_static,json=isStatic,proto3" json:"is_static,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Collider) Reset() {
	*x = Collider{}
	mi := &file_server_packet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Collider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Collider) ProtoMessage() {}

func (x *Collider) ProtoReflect() protoreflect.Message {
	mi := &file_server_packet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Collider.ProtoReflect.Descriptor instead.
func (*Collider) Descriptor() ([]byte, []int) {
	return file_server_packet_proto_rawDescGZIP(), []int{0}
}

func (x *Collider) GetType() Collider_ColliderType {
	if x != nil {
		return x.Type
	}
	return Collider_COLLIDER_TYPE_UNSPECIFIED
}

func (x *Collider) GetRotation() float64 {
	if x != nil {
		return x.Rotation
	}
	return 0
}

func (x *Collider) GetSize() *Vec2 {
	if x != nil {
		return x.Size
	}
	return nil
}

func (x *Collider) GetRadius() float64 {
	if x != nil {
		return x.Radius
	}
	return 0
}

func (x *Collider) GetPosition() *Vec2 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Collider) GetVelocity() *Vec2 {
	if x != nil {
		return x.Velocity
	}
	return nil
}

func (x *Collider) GetIsStatic() bool {
	if x != nil {
		return x.IsStatic
	}
	return false
}

type RenderData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sprite        RenderData_Sprite      `protobuf:"varint,1,opt,name=sprite,proto3,enum=spellfire.RenderData_Sprite" json:"sprite,omitempty"`
	SpriteSize    float64                `protobuf:"fixed64,2,opt,name=sprite_size,json=spriteSize,proto3" json:"sprite_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderData) Reset() {
	*x = RenderData{}
	mi := &file_server_packet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderData) ProtoMessage() {}

func (x *RenderData) ProtoReflect() protoreflect.Message {
	mi := &file_server_packet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderData.ProtoReflect.Descriptor instead.
func (*RenderData) Descriptor() ([]byte, []int) {
	return file_server_packet_proto_rawDescGZIP(), []int{1}
}

func (x *RenderData) GetSprite() RenderData_Sprite {
	if x != nil {
		return x.Sprite
	}
	return RenderData_SPRITE_UNSPECIFIED
}

func (x *RenderData) GetSpriteSize() float64 {
	if x != nil {
		return x.SpriteSize
	}
	return 0
}

type EntityAttribute struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Type          EntityAttribute_EntityAttributeType `protobuf:"varint,1,opt,name=type,proto3,enum=spellfire.EntityAttribute_EntityAttributeType" json:"type,omitempty"`
	Name          string                              `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Health        float64                             `protobuf:"fixed64,3,opt,name=health,proto3" json:"health,omitempty"`
	Gun           Gun                                 `protobuf:"varint,4,opt,name=gun,proto3,enum=spellfire.Gun" json:"gun,omitempty"`
	Damage        float64                             `protobuf:"fixed64,5,opt,name=damage,proto3" json:"damage,omitempty"`
	SpellsFired   []Spell                             `protobuf:"varint,6,rep,packed,name=spells_fired,json=spellsFired,proto3,enum=spellfire.Spell" json:"spells_fired,omitempty"`
	SpellFireTime *Timestamp                          `protobuf:"bytes,7,opt,name=spell_fire_time,json=spellFireTime,proto3" json:"spell_fire_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityAttribute) Reset() {
	*x = EntityAttribute{}
	mi := &file_server_packet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityAttribute) ProtoMessage() {}

func (x *EntityAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_server_packet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityAttribute.ProtoReflect.Descriptor instead.
func (*EntityAttribute) Descriptor() ([]byte, []int) {
	return file_server_packet_proto_rawDescGZIP(), []int{2}
}

func (x *EntityAttribute) GetType() EntityAttribute_EntityAttributeType {
	if x != nil {
		return x.Type
	}
	return EntityAttribute_ENTITY_ATTRIBUTE_TYPE_UNSPECIFIED
}

func (x *EntityAttribute) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EntityAttribute) GetHealth() float64 {
	if x != nil {
		return x.Health
	}
	return 0
}

func (x *EntityAttribute) GetGun() Gun {
	if x != nil {
		return x.Gun
	}
	return Gun_GUN_UNSPECIFIED
}

func (x *EntityAttribute) GetDamage() float64 {
	if x != nil {
		return x.Damage
	}
	return 0
}

func (x *EntityAttribute) GetSpellsFired() []Spell {
	if x != nil {
		return x.SpellsFired
	}
	return nil
}

func (x *EntityAttribute) GetSpellFireTime() *Timestamp {
	if x != nil {
		return x.SpellFireTime
	}
	return nil
}

type Entity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          Entity_EntityType      `protobuf:"varint,2,opt,name=type,proto3,enum=spellfire.Entity_EntityType" json:"type,omitempty"`
	Collider      *Collider              `protobuf:"bytes,3,opt,name=collider,proto3" json:"collider,omitempty"`
	RenderData    *RenderData            `protobuf:"bytes,4,opt,name=render_data,json=renderData,proto3" json:"render_data,omitempty"`
	States        []Entity_EntityState   `protobuf:"varint,5,rep,packed,name=states,proto3,enum=spellfire.Entity_EntityState" json:"states,omitempty"`
	Attributes    []*EntityAttribute     `protobuf:"bytes,6,rep,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity) Reset() {
	*x = Entity{}
	mi := &file_server_packet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_server_packet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_server_packet_proto_rawDescGZIP(), []int{3}
}

func (x *Entity) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Entity) GetType() Entity_EntityType {
	if x != nil {
		return x.Type
	}
	return Entity_ENTITY_TYPE_UNSPECIFIED
}

func (x *Entity) GetCollider() *Collider {
	if x != nil {
		return x.Collider
	}
	return nil
}

func (x *Entity) GetRenderData() *RenderData {
	if x != nil {
		return x.RenderData
	}
	return nil
}

func (x *Entity) GetStates() []Entity_EntityState {
	if x != nil {
		return x.States
	}
	return nil
}

func (x *Entity) GetAttributes() []*EntityAttribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type ServerEvent struct {
	state             protoimpl.MessageState      `protogen:"open.v1"`
	Type              ServerEvent_ServerEventType `protobuf:"varint,1,opt,name=type,proto3,enum=spellfire.ServerEvent_ServerEventType" json:"type,omitempty"`
	EnterGamePlayerId uint32                      `protobuf:"varint,2,opt,name=enter_game_player_id,json=enterGamePlayerId,proto3" json:"enter_game_player_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ServerEvent) Reset() {
	*x = ServerEvent{}
	mi := &file_server_packet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEvent) ProtoMessage() {}

func (x *ServerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_server_packet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEvent.ProtoReflect.Descriptor instead.
func (*ServerEvent) Descriptor() ([]byte, []int) {
	return file_server_packet_proto_rawDescGZIP(), []int{4}
}

func (x *ServerEvent) GetType() ServerEvent_ServerEventType {
	if x != nil {
		return x.Type
	}
	return ServerEvent_SERVER_EVENT_TYPE_UNSPECIFIED
}

func (x *ServerEvent) GetEnterGamePlayerId() uint32 {
	if x != nil {
		return x.EnterGamePlayerId
	}
	return 0
}

type ServerPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *Timestamp             `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Entities      []*Entity              `protobuf:"bytes,2,rep,name=entities,proto3" json:"entities,omitempty"`
	Events        []*ServerEvent         `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerPacket) Reset() {
	*x = ServerPacket{}
	mi := &file_server_packet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerPacket) ProtoMessage() {}

func (x *ServerPacket) ProtoReflect() protoreflect.Message {
	mi := &file_server_packet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerPacket.ProtoReflect.Descriptor instead.
func (*ServerPacket) Descriptor() ([]byte, []int) {
	return file_server_packet_proto_rawDescGZIP(), []int{5}
}

func (x *ServerPacket) GetTimestamp() *Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ServerPacket) GetEntities() []*Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *ServerPacket) GetEvents() []*ServerEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_server_packet_proto protoreflect.FileDescriptor

const file_server_packet_proto_rawDesc = "" +
	"\n" +
	"\x13server_packet.proto\x12\tspellfire\x1a\vtypes.proto\x1a\n" +
	"mage.proto\"\xe0\x02\n" +
	"\bCollider\x124\n" +
	"\x04type\x18\x01 \x01(\x0e2 .spellfire.Collider.ColliderTypeR\x04type\x12\x1a\n" +
	"\brotation\x18\x02 \x01(\x01R\brotation\x12#\n" +
	"\x04size\x18\x03 \x01(\v2\x0f.spellfire.Vec2R\x04size\x12\x16\n" +
	"\x06radius\x18\x04 \x01(\x01R\x06radius\x12+\n" +
	"\bposition\x18\x05 \x01(\v2\x0f.spellfire.Vec2R\bposition\x12+\n" +
	"\bvelocity\x18\x06 \x01(\v2\x0f.spellfire.Vec2R\bvelocity\x12\x1b\n" +
	"\tis_static\x18\a \x01(\bR\bisStatic\"N\n" +
	"\fColliderType\x12\x1d\n" +
	"\x19COLLIDER_TYPE_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05POINT\x10\x01\x12\n" +
	"\n" +
	"\x06CIRCLE\x10\x02\x12\b\n" +
	"\x04RECT\x10\x03\"\xae\x02\n" +
	"\n" +
	"RenderData\x124\n" +
	"\x06sprite\x18\x01 \x01(\x0e2\x1c.spellfire.RenderData.SpriteR\x06sprite\x12\x1f\n" +
	"\vsprite_size\x18\x02 \x01(\x01R\n" +
	"spriteSize\"\xc8\x01\n" +
	"\x06Sprite\x12\x16\n" +
	"\x12SPRITE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06GUNNER\x10\x01\x12\b\n" +
	"\x04MAGE\x10\x02\x12\f\n" +
	"\bBULLET_1\x10\x03\x12\n" +
	"\n" +
	"\x06BUSH_1\x10\x04\x12\n" +
	"\n" +
	"\x06TREE_1\x10\x05\x12\n" +
	"\n" +
	"\x06TREE_2\x10\x06\x12\n" +
	"\n" +
	"\x06ROCK_1\x10\a\x12\n" +
	"\n" +
	"\x06ROCK_2\x10\b\x12\n" +
	"\n" +
	"\x06ROCK_3\x10\t\x12\n" +
	"\n" +
	"\x06ROCK_4\x10\n" +
	"\x12\x0f\n" +
	"\vDEAD_BUSH_1\x10\v\x12\x0f\n" +
	"\vDEAD_BUSH_2\x10\f\x12\f\n" +
	"\bCACTUS_1\x10\r\"\xdd\x03\n" +
	"\x0fEntityAttribute\x12B\n" +
	"\x04type\x18\x01 \x01(\x0e2..spellfire.EntityAttribute.EntityAttributeTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06health\x18\x03 \x01(\x01R\x06health\x12 \n" +
	"\x03gun\x18\x04 \x01(\x0e2\x0e.spellfire.GunR\x03gun\x12\x16\n" +
	"\x06damage\x18\x05 \x01(\x01R\x06damage\x123\n" +
	"\fspells_fired\x18\x06 \x03(\x0e2\x10.spellfire.SpellR\vspellsFired\x12<\n" +
	"\x0fspell_fire_time\x18\a \x01(\v2\x14.spellfire.TimestampR\rspellFireTime\"\xac\x01\n" +
	"\x13EntityAttributeType\x12%\n" +
	"!ENTITY_ATTRIBUTE_TYPE_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04NAME\x10\x01\x12\n" +
	"\n" +
	"\x06HEALTH\x10\x02\x12\a\n" +
	"\x03GUN\x10\x03\x12\n" +
	"\n" +
	"\x06DAMAGE\x10\x04\x12\x15\n" +
	"\x11SPELL_1_LAST_FIRE\x10\x05\x12\x15\n" +
	"\x11SPELL_2_LAST_FIRE\x10\x06\x12\x15\n" +
	"\x11SPELL_3_LAST_FIRE\x10\a\"\xda\x03\n" +
	"\x06Entity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x120\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1c.spellfire.Entity.EntityTypeR\x04type\x12/\n" +
	"\bcollider\x18\x03 \x01(\v2\x13.spellfire.ColliderR\bcollider\x126\n" +
	"\vrender_data\x18\x04 \x01(\v2\x15.spellfire.RenderDataR\n" +
	"renderData\x125\n" +
	"\x06states\x18\x05 \x03(\x0e2\x1d.spellfire.Entity.EntityStateR\x06states\x12:\n" +
	"\n" +
	"attributes\x18\x06 \x03(\v2\x1a.spellfire.EntityAttributeR\n" +
	"attributes\"\x84\x01\n" +
	"\n" +
	"EntityType\x12\x1b\n" +
	"\x17ENTITY_TYPE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06GUNNER\x10\x01\x12\b\n" +
	"\x04MAGE\x10\x02\x12\n" +
	"\n" +
	"\x06BULLET\x10\x03\x12\b\n" +
	"\x04BUSH\x10\x04\x12\b\n" +
	"\x04TREE\x10\x05\x12\b\n" +
	"\x04ROCK\x10\x06\x12\r\n" +
	"\tDEAD_BUSH\x10\a\x12\n" +
	"\n" +
	"\x06CACTUS\x10\b\"+\n" +
	"\vEntityState\x12\x1c\n" +
	"\x18ENTITY_STATE_UNSPECIFIED\x10\x00\"\xc0\x01\n" +
	"\vServerEvent\x12:\n" +
	"\x04type\x18\x01 \x01(\x0e2&.spellfire.ServerEvent.ServerEventTypeR\x04type\x12/\n" +
	"\x14enter_game_player_id\x18\x02 \x01(\rR\x11enterGamePlayerId\"D\n" +
	"\x0fServerEventType\x12!\n" +
	"\x1dSERVER_EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"ENTER_GAME\x10\x01\"\xa1\x01\n" +
	"\fServerPacket\x122\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x14.spellfire.TimestampR\ttimestamp\x12-\n" +
	"\bentities\x18\x02 \x03(\v2\x11.spellfire.EntityR\bentities\x12.\n" +
	"\x06events\x18\x03 \x03(\v2\x16.spellfire.ServerEventR\x06events*3\n" +
	"\x03Gun\x12\x13\n" +
	"\x0fGUN_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13GUN_AUTOMATIC_RIFLE\x10\x01B?Z=github.com/Icemaster-Eric/Spellfire/backend/internal/proto;pbb\x06proto3"

var (
	file_server_packet_proto_rawDescOnce sync.Once
	file_server_packet_proto_rawDescData []byte
)

func file_server_packet_proto_rawDescGZIP() []byte {
	file_server_packet_proto_rawDescOnce.Do(func() {
		file_server_packet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_packet_proto_rawDesc), len(file_server_packet_proto_rawDesc)))
	})
	return file_server_packet_proto_rawDescData
}

var file_server_packet_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_server_packet_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_server_packet_proto_goTypes = []any{
	(Gun)(0),                                 // 0: spellfire.Gun
	(Collider_ColliderType)(0),               // 1: spellfire.Collider.ColliderType
	(RenderData_Sprite)(0),                   // 2: spellfire.RenderData.Sprite
	(EntityAttribute_EntityAttributeType)(0), // 3: spellfire.EntityAttribute.EntityAttributeType
	(Entity_EntityType)(0),                   // 4: spellfire.Entity.EntityType
	(Entity_EntityState)(0),                  // 5: spellfire.Entity.EntityState
	(ServerEvent_ServerEventType)(0),         // 6: spellfire.ServerEvent.ServerEventType
	(*Collider)(nil),                         // 7: spellfire.Collider
	(*RenderData)(nil),                       // 8: spellfire.RenderData
	(*EntityAttribute)(nil),                  // 9: spellfire.EntityAttribute
	(*Entity)(nil),                           // 10: spellfire.Entity
	(*ServerEvent)(nil),                      // 11: spellfire.ServerEvent
	(*ServerPacket)(nil),                     // 12: spellfire.ServerPacket
	(*Vec2)(nil),                             // 13: spellfire.Vec2
	(Spell)(0),                               // 14: spellfire.Spell
	(*Timestamp)(nil),                        // 15: spellfire.Timestamp
}
var file_server_packet_proto_depIdxs = []int32{
	1,  // 0: spellfire.Collider.type:type_name -> spellfire.Collider.ColliderType
	13, // 1: spellfire.Collider.size:type_name -> spellfire.Vec2
	13, // 2: spellfire.Collider.position:type_name -> spellfire.Vec2
	13, // 3: spellfire.Collider.velocity:type_name -> spellfire.Vec2
	2,  // 4: spellfire.RenderData.sprite:type_name -> spellfire.RenderData.Sprite
	3,  // 5: spellfire.EntityAttribute.type:type_name -> spellfire.EntityAttribute.EntityAttributeType
	0,  // 6: spellfire.EntityAttribute.gun:type_name -> spellfire.Gun
	14, // 7: spellfire.EntityAttribute.spells_fired:type_name -> spellfire.Spell
	15, // 8: spellfire.EntityAttribute.spell_fire_time:type_name -> spellfire.Timestamp
	4,  // 9: spellfire.Entity.type:type_name -> spellfire.Entity.EntityType
	7,  // 10: spellfire.Entity.collider:type_name -> spellfire.Collider
	8,  // 11: spellfire.Entity.render_data:type_name -> spellfire.RenderData
	5,  // 12: spellfire.Entity.states:type_name -> spellfire.Entity.EntityState
	9,  // 13: spellfire.Entity.attributes:type_name -> spellfire.EntityAttribute
	6,  // 14: spellfire.ServerEvent.type:type_name -> spellfire.ServerEvent.ServerEventType
	15, // 15: spellfire.ServerPacket.timestamp:type_name -> spellfire.Timestamp
	10, // 16: spellfire.ServerPacket.entities:type_name -> spellfire.Entity
	11, // 17: spellfire.ServerPacket.events:type_name -> spellfire.ServerEvent
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_server_packet_proto_init() }
func file_server_packet_proto_init() {
	if File_server_packet_proto != nil {
		return
	}
	file_types_proto_init()
	file_mage_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_packet_proto_rawDesc), len(file_server_packet_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_server_packet_proto_goTypes,
		DependencyIndexes: file_server_packet_proto_depIdxs,
		EnumInfos:         file_server_packet_proto_enumTypes,
		MessageInfos:      file_server_packet_proto_msgTypes,
	}.Build()
	File_server_packet_proto = out.File
	file_server_packet_proto_goTypes = nil
	file_server_packet_proto_depIdxs = nil
}
