// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: server_packet.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntityType int32

const (
	EntityType_ENTITY_TYPE_UNSPECIFIED EntityType = 0
	EntityType_PLAYER                  EntityType = 1
)

// Enum value maps for EntityType.
var (
	EntityType_name = map[int32]string{
		0: "ENTITY_TYPE_UNSPECIFIED",
		1: "PLAYER",
	}
	EntityType_value = map[string]int32{
		"ENTITY_TYPE_UNSPECIFIED": 0,
		"PLAYER":                  1,
	}
)

func (x EntityType) Enum() *EntityType {
	p := new(EntityType)
	*p = x
	return p
}

func (x EntityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntityType) Descriptor() protoreflect.EnumDescriptor {
	return file_server_packet_proto_enumTypes[0].Descriptor()
}

func (EntityType) Type() protoreflect.EnumType {
	return &file_server_packet_proto_enumTypes[0]
}

func (x EntityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntityType.Descriptor instead.
func (EntityType) EnumDescriptor() ([]byte, []int) {
	return file_server_packet_proto_rawDescGZIP(), []int{0}
}

type EntityAttribute int32

const (
	EntityAttribute_ENTITY_ATTRIBUTE_UNSPECIFIED EntityAttribute = 0
)

// Enum value maps for EntityAttribute.
var (
	EntityAttribute_name = map[int32]string{
		0: "ENTITY_ATTRIBUTE_UNSPECIFIED",
	}
	EntityAttribute_value = map[string]int32{
		"ENTITY_ATTRIBUTE_UNSPECIFIED": 0,
	}
)

func (x EntityAttribute) Enum() *EntityAttribute {
	p := new(EntityAttribute)
	*p = x
	return p
}

func (x EntityAttribute) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntityAttribute) Descriptor() protoreflect.EnumDescriptor {
	return file_server_packet_proto_enumTypes[1].Descriptor()
}

func (EntityAttribute) Type() protoreflect.EnumType {
	return &file_server_packet_proto_enumTypes[1]
}

func (x EntityAttribute) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntityAttribute.Descriptor instead.
func (EntityAttribute) EnumDescriptor() ([]byte, []int) {
	return file_server_packet_proto_rawDescGZIP(), []int{1}
}

type EntityState int32

const (
	EntityState_ENTITY_STATE_UNSPECIFIED EntityState = 0
)

// Enum value maps for EntityState.
var (
	EntityState_name = map[int32]string{
		0: "ENTITY_STATE_UNSPECIFIED",
	}
	EntityState_value = map[string]int32{
		"ENTITY_STATE_UNSPECIFIED": 0,
	}
)

func (x EntityState) Enum() *EntityState {
	p := new(EntityState)
	*p = x
	return p
}

func (x EntityState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntityState) Descriptor() protoreflect.EnumDescriptor {
	return file_server_packet_proto_enumTypes[2].Descriptor()
}

func (EntityState) Type() protoreflect.EnumType {
	return &file_server_packet_proto_enumTypes[2]
}

func (x EntityState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntityState.Descriptor instead.
func (EntityState) EnumDescriptor() ([]byte, []int) {
	return file_server_packet_proto_rawDescGZIP(), []int{2}
}

type ServerEventType int32

const (
	ServerEventType_SERVER_EVENT_TYPE_UNSPECIFIED ServerEventType = 0
)

// Enum value maps for ServerEventType.
var (
	ServerEventType_name = map[int32]string{
		0: "SERVER_EVENT_TYPE_UNSPECIFIED",
	}
	ServerEventType_value = map[string]int32{
		"SERVER_EVENT_TYPE_UNSPECIFIED": 0,
	}
)

func (x ServerEventType) Enum() *ServerEventType {
	p := new(ServerEventType)
	*p = x
	return p
}

func (x ServerEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_server_packet_proto_enumTypes[3].Descriptor()
}

func (ServerEventType) Type() protoreflect.EnumType {
	return &file_server_packet_proto_enumTypes[3]
}

func (x ServerEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerEventType.Descriptor instead.
func (ServerEventType) EnumDescriptor() ([]byte, []int) {
	return file_server_packet_proto_rawDescGZIP(), []int{3}
}

type Entity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          EntityType             `protobuf:"varint,2,opt,name=type,proto3,enum=spellfire.EntityType" json:"type,omitempty"`
	Position      *Vec2                  `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Rotation      float64                `protobuf:"fixed64,4,opt,name=rotation,proto3" json:"rotation,omitempty"`
	Velocity      *Vec2                  `protobuf:"bytes,5,opt,name=velocity,proto3" json:"velocity,omitempty"`
	Attributes    []EntityAttribute      `protobuf:"varint,6,rep,packed,name=attributes,proto3,enum=spellfire.EntityAttribute" json:"attributes,omitempty"`
	States        []EntityState          `protobuf:"varint,7,rep,packed,name=states,proto3,enum=spellfire.EntityState" json:"states,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity) Reset() {
	*x = Entity{}
	mi := &file_server_packet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_server_packet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_server_packet_proto_rawDescGZIP(), []int{0}
}

func (x *Entity) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Entity) GetType() EntityType {
	if x != nil {
		return x.Type
	}
	return EntityType_ENTITY_TYPE_UNSPECIFIED
}

func (x *Entity) GetPosition() *Vec2 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Entity) GetRotation() float64 {
	if x != nil {
		return x.Rotation
	}
	return 0
}

func (x *Entity) GetVelocity() *Vec2 {
	if x != nil {
		return x.Velocity
	}
	return nil
}

func (x *Entity) GetAttributes() []EntityAttribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Entity) GetStates() []EntityState {
	if x != nil {
		return x.States
	}
	return nil
}

type ServerEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ServerEventType        `protobuf:"varint,1,opt,name=type,proto3,enum=spellfire.ServerEventType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerEvent) Reset() {
	*x = ServerEvent{}
	mi := &file_server_packet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEvent) ProtoMessage() {}

func (x *ServerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_server_packet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEvent.ProtoReflect.Descriptor instead.
func (*ServerEvent) Descriptor() ([]byte, []int) {
	return file_server_packet_proto_rawDescGZIP(), []int{1}
}

func (x *ServerEvent) GetType() ServerEventType {
	if x != nil {
		return x.Type
	}
	return ServerEventType_SERVER_EVENT_TYPE_UNSPECIFIED
}

type ServerPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *Timestamp             `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Entities      []*Entity              `protobuf:"bytes,2,rep,name=entities,proto3" json:"entities,omitempty"`
	Events        []*ServerEvent         `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerPacket) Reset() {
	*x = ServerPacket{}
	mi := &file_server_packet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerPacket) ProtoMessage() {}

func (x *ServerPacket) ProtoReflect() protoreflect.Message {
	mi := &file_server_packet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerPacket.ProtoReflect.Descriptor instead.
func (*ServerPacket) Descriptor() ([]byte, []int) {
	return file_server_packet_proto_rawDescGZIP(), []int{2}
}

func (x *ServerPacket) GetTimestamp() *Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ServerPacket) GetEntities() []*Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *ServerPacket) GetEvents() []*ServerEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_server_packet_proto protoreflect.FileDescriptor

const file_server_packet_proto_rawDesc = "" +
	"\n" +
	"\x13server_packet.proto\x12\tspellfire\x1a\vtypes.proto\"\xa5\x02\n" +
	"\x06Entity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12)\n" +
	"\x04type\x18\x02 \x01(\x0e2\x15.spellfire.EntityTypeR\x04type\x12+\n" +
	"\bposition\x18\x03 \x01(\v2\x0f.spellfire.Vec2R\bposition\x12\x1a\n" +
	"\brotation\x18\x04 \x01(\x01R\brotation\x12+\n" +
	"\bvelocity\x18\x05 \x01(\v2\x0f.spellfire.Vec2R\bvelocity\x12:\n" +
	"\n" +
	"attributes\x18\x06 \x03(\x0e2\x1a.spellfire.EntityAttributeR\n" +
	"attributes\x12.\n" +
	"\x06states\x18\a \x03(\x0e2\x16.spellfire.EntityStateR\x06states\"=\n" +
	"\vServerEvent\x12.\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1a.spellfire.ServerEventTypeR\x04type\"\xa1\x01\n" +
	"\fServerPacket\x122\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x14.spellfire.TimestampR\ttimestamp\x12-\n" +
	"\bentities\x18\x02 \x03(\v2\x11.spellfire.EntityR\bentities\x12.\n" +
	"\x06events\x18\x03 \x03(\v2\x16.spellfire.ServerEventR\x06events*5\n" +
	"\n" +
	"EntityType\x12\x1b\n" +
	"\x17ENTITY_TYPE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06PLAYER\x10\x01*3\n" +
	"\x0fEntityAttribute\x12 \n" +
	"\x1cENTITY_ATTRIBUTE_UNSPECIFIED\x10\x00*+\n" +
	"\vEntityState\x12\x1c\n" +
	"\x18ENTITY_STATE_UNSPECIFIED\x10\x00*4\n" +
	"\x0fServerEventType\x12!\n" +
	"\x1dSERVER_EVENT_TYPE_UNSPECIFIED\x10\x00B?Z=github.com/Icemaster-Eric/Spellfire/backend/internal/proto;pbb\x06proto3"

var (
	file_server_packet_proto_rawDescOnce sync.Once
	file_server_packet_proto_rawDescData []byte
)

func file_server_packet_proto_rawDescGZIP() []byte {
	file_server_packet_proto_rawDescOnce.Do(func() {
		file_server_packet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_packet_proto_rawDesc), len(file_server_packet_proto_rawDesc)))
	})
	return file_server_packet_proto_rawDescData
}

var file_server_packet_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_server_packet_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_server_packet_proto_goTypes = []any{
	(EntityType)(0),      // 0: spellfire.EntityType
	(EntityAttribute)(0), // 1: spellfire.EntityAttribute
	(EntityState)(0),     // 2: spellfire.EntityState
	(ServerEventType)(0), // 3: spellfire.ServerEventType
	(*Entity)(nil),       // 4: spellfire.Entity
	(*ServerEvent)(nil),  // 5: spellfire.ServerEvent
	(*ServerPacket)(nil), // 6: spellfire.ServerPacket
	(*Vec2)(nil),         // 7: spellfire.Vec2
	(*Timestamp)(nil),    // 8: spellfire.Timestamp
}
var file_server_packet_proto_depIdxs = []int32{
	0, // 0: spellfire.Entity.type:type_name -> spellfire.EntityType
	7, // 1: spellfire.Entity.position:type_name -> spellfire.Vec2
	7, // 2: spellfire.Entity.velocity:type_name -> spellfire.Vec2
	1, // 3: spellfire.Entity.attributes:type_name -> spellfire.EntityAttribute
	2, // 4: spellfire.Entity.states:type_name -> spellfire.EntityState
	3, // 5: spellfire.ServerEvent.type:type_name -> spellfire.ServerEventType
	8, // 6: spellfire.ServerPacket.timestamp:type_name -> spellfire.Timestamp
	4, // 7: spellfire.ServerPacket.entities:type_name -> spellfire.Entity
	5, // 8: spellfire.ServerPacket.events:type_name -> spellfire.ServerEvent
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_server_packet_proto_init() }
func file_server_packet_proto_init() {
	if File_server_packet_proto != nil {
		return
	}
	file_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_packet_proto_rawDesc), len(file_server_packet_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_server_packet_proto_goTypes,
		DependencyIndexes: file_server_packet_proto_depIdxs,
		EnumInfos:         file_server_packet_proto_enumTypes,
		MessageInfos:      file_server_packet_proto_msgTypes,
	}.Build()
	File_server_packet_proto = out.File
	file_server_packet_proto_goTypes = nil
	file_server_packet_proto_depIdxs = nil
}
